# Generated by Django 4.1 on 2022-10-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_nome', models.CharField(max_length=120)),
                ('pos_cep', models.CharField(max_length=45)),
                ('pos_rua', models.CharField(max_length=45)),
                ('pos_bairro', models.CharField(max_length=45)),
                ('pos_numero', models.IntegerField()),
                ('pos_logradouro', models.CharField(max_length=45)),
                ('pos_telefone', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Postos',
            },
        ),
        migrations.CreateModel(
            name='vacinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_tipo_vacina', models.CharField(max_length=120)),
                ('vac_lote', models.CharField(max_length=45)),
                ('vac_fabricante', models.CharField(max_length=45)),
                ('vac_descricao', models.CharField(max_length=300)),
                ('vac_quantidade', models.IntegerField()),
                ('vac_disponibilidade', models.BooleanField()),
                ('vac_contraindicacao', models.CharField(max_length=300)),
                ('vac_reacoes', models.CharField(max_length=300)),
                ('vac_data_fabricacao', models.DateField()),
                ('vac_data_validade', models.DateField()),
                ('vac_data_recebimento', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Vacinas',
            },
        ),
    ]
