# Generated by Django 4.1.2 on 2022-11-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postos',
            name='pos_vacinas',
            field=models.ManyToManyField(to='core.vacinas'),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_contraindicacao',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_descricao',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_reacoes',
            field=models.TextField(max_length=300),
        ),
    ]
