# Generated by Django 4.1.2 on 2022-11-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postos_pos_vacinas_alter_vacinas_vac_contraindicacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postos',
            name='pos_vacinas',
        ),
        migrations.AddField(
            model_name='vacinas',
            name='pos_postos',
            field=models.ManyToManyField(to='core.postos'),
        ),
    ]
