# Generated by Django 4.1.2 on 2022-11-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_postos_pos_vacinas_vacinas_pos_postos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacinas',
            old_name='pos_postos',
            new_name='vac_postos',
        ),
    ]
