# Generated by Django 4.1.2 on 2022-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_pos_postos_vacinas_vac_postos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinas',
            name='vac_data_fabricacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_data_recebimento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_data_validade',
            field=models.DateTimeField(),
        ),
    ]
