# Generated by Django 4.1.2 on 2022-11-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vacinas_vac_data_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinas',
            name='vac_data_fabricacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_data_recebimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_data_validade',
            field=models.DateField(),
        ),
    ]
