# Generated by Django 4.1.2 on 2022-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_vacinas_vac_postos_vacinas_vac_posto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacinas',
            name='vac_posto',
        ),
        migrations.AddField(
            model_name='vacinas',
            name='vac_postos',
            field=models.ManyToManyField(to='core.postos'),
        ),
    ]
