# Generated by Django 4.1.2 on 2022-11-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_vacinas_vac_posto_vacinas_vac_postos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacinas',
            name='vac_postos',
        ),
        migrations.AddField(
            model_name='vacinas',
            name='vac_posto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Vacinas', to='core.postos'),
        ),
    ]
