# Generated by Django 4.1.2 on 2022-11-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_vacinas_vac_postos_vacinas_vac_posto'),
    ]

    operations = [
        migrations.CreateModel(
            name='dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_dia', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_disponibilidade',
            field=models.BooleanField(choices=[[1, 'Disponível'], [0, 'Indisponível']], default=1),
        ),
        migrations.AlterField(
            model_name='vacinas',
            name='vac_posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vacinas', to='core.postos'),
        ),
        migrations.AddField(
            model_name='vacinas',
            name='vac_dias',
            field=models.ManyToManyField(related_name='Vacinas', to='core.dias'),
        ),
    ]
