# Generated by Django 4.1.2 on 2022-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dias_alter_vacinas_vac_disponibilidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias',
            name='dis_dia',
            field=models.CharField(choices=[[1, 'Domingo'], [2, 'Segunda-feira'], [3, 'Terça-feira'], [4, 'Quarta-feira'], [5, 'Quinta-feira'], [6, 'Sexta-feira'], [7, 'Sábado']], max_length=20),
        ),
    ]
